name: Build and release beta
on:
  push:
    branches:
      - 'main'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name:
        uses: bufbuild/buf-setup-action@v1
        with:
          version: latest
      - run: buf --version
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.MYNA_APP_ID }}
          private-key: ${{ secrets.MYNA_APP_SECRET }}
      - name: 'bot: version bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          PACKAGEJSON_DIR: 'js'
        with:
          version-type: 'prerelease'
          commit-message: 'bump version'
          skip-tag: 'true'
          skip-commit:  'false'
      - name: Build and publish
        run: |
          bash generate.sh
          cd js
          buf generate
          pnpm install
          pnpm run build
          npm config set '//registry.npmjs.org/:_authToken' $NPM_TOKEN
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
