name: Build and release proto js
on:
  release:
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name:
        uses: bufbuild/buf-setup-action@v1
        with:
          version: latest
      - run: buf --version
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
      - name: Build and publish
        run: |
          bash generate.sh
          cd js
          buf generate
          pnpm install
          pnpm run build
          pnpm config set '//registry.npmjs.org/:_authToken' $NPM_TOKEN
          pnpm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
